// Gamestone Engine
// Licensed under the LGPL

// Local includes
#include <Gamestone/Utility/Actions_wrapper.h>

//===============================================================================================
void register_Actions()
{
    // Expose enum
    REGISTER_ENUM_HEADER(Gamestone::KeyboardEnumBase, "KeyboardEnum")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::A, "A")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::B, "B")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::C, "C")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::D, "D")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::E, "E")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F, "F")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::G, "G")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::H, "H")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::I, "I")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::J, "J")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::K, "K")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::L, "L")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::M, "M")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::N, "N")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::O, "O")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::P, "P")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Q, "Q")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::R, "R")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::S, "S")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::T, "T")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::U, "U")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::V, "V")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::W, "W")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::X, "X")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Y, "Y")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Z, "Z")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num0, "Num0")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num1, "Num1")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num2, "Num2")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num3, "Num3")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num4, "Num4")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num5, "Num5")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num6, "Num6")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num7, "Num7")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num8, "Num8")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Num9, "Num9")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Escape, "Escape")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::LControl, "LControl")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::LShift, "LShift")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::LAlt, "LAlt")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::LSystem, "LSystem")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::RControl, "RControl")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::RShift, "RShift")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::RAlt, "RAlt")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::RSystem, "RSystem")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Menu, "Menu")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::LBracket, "LBracket")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::RBracket, "RBracket")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::SemiColon, "SemiColon")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Comma, "Comma")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Period, "Period")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Quote, "Quote")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Slash, "Slash")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::BackSlash, "BackSlash")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Tilde, "Tilde")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Equal, "Equal")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Dash, "Dash")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Space, "Space")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Return, "Return")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::BackSpace, "BackSpace")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Tab, "Tab")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::PageUp, "PageUp")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::PageDown, "PageDown")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::End, "End")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Home, "Home")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Insert, "Insert")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Delete, "Delete")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Add, "Add")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Subtract, "Subtract")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Multiply, "Multiply")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Divide, "Divide")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Left, "Left")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Right, "Right")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Up, "Up")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Down, "Down")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad0, "Numpad0")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad1, "Numpad1")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad2, "Numpad2")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad3, "Numpad3")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad4, "Numpad4")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad5, "Numpad5")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad6, "Numpad6")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad7, "Numpad7")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad8, "Numpad8")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Numpad9, "Numpad9")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F1, "F1")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F2, "F2")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F3, "F3")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F4, "F4")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F5, "F5")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F6, "F6")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F7, "F7")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F8, "F8")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F9, "F9")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F10, "F10")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F11, "F11")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F12, "F12")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F13, "F13")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F14, "F14")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::F15, "F15")
    REGISTER_ENUM_VALUE(Gamestone::KeyboardEnum::Pause, "Pause")
    REGISTER_ENUM_FOOTER()
    
    // Expose enum
    REGISTER_ENUM_HEADER(Gamestone::MouseEnumBase, "MouseEnum")
    REGISTER_ENUM_VALUE(Gamestone::MouseEnum::Left, "Left")
    REGISTER_ENUM_VALUE(Gamestone::MouseEnum::Right, "Right")
    REGISTER_ENUM_VALUE(Gamestone::MouseEnum::Middle, "Middle")
    REGISTER_ENUM_VALUE(Gamestone::MouseEnum::XButton1, "XButton1")
    REGISTER_ENUM_VALUE(Gamestone::MouseEnum::XButton2, "XButton2")
    REGISTER_ENUM_FOOTER()
    
    // Expose enum
    REGISTER_ENUM_HEADER(Gamestone::EventEnumBase, "EventEnum")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::Closed, "Closed")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::Resized, "Resized")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::LostFocus, "LostFocus")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::GainedFocus, "GainedFocus")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::TextEntered, "TextEntered")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::KeyPressed, "KeyPressed")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::KeyReleased, "KeyReleased")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::MouseWheelMoved, "MouseWheelMoved")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::MouseButtonPressed, "MouseButtonPressed")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::MouseButtonReleased, "MouseButtonReleased")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::MouseMoved, "MouseMoved")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::MouseEntered, "MouseEntered")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::MouseLeft, "MouseLeft")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::JoystickButtonPressed, "JoystickButtonPressed")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::JoystickButtonReleased, "JoystickButtonReleased")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::JoystickMoved, "JoystickMoved")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::JoystickConnected, "JoystickConnected")
    REGISTER_ENUM_VALUE(Gamestone::EventEnum::JoystickDisconnected, "JoystickDisconnected")
    REGISTER_ENUM_FOOTER()
    
    // Expose enum
    REGISTER_ENUM_HEADER(Gamestone::ActionEnumBase, "ActionEnum")
    REGISTER_ENUM_VALUE(Gamestone::ActionEnum::Hold, "Hold")
    REGISTER_ENUM_VALUE(Gamestone::ActionEnum::PressOnce, "PressOnce")
    REGISTER_ENUM_VALUE(Gamestone::ActionEnum::ReleaseOnce, "ReleaseOnce")
    REGISTER_ENUM_FOOTER()
    
    // Expose class
    REGISTER_CLASS_HEADER_CONSTRUCT(Gamestone::Action, "Action")
    REGISTER_CLASS_INIT2(Gamestone::KeyboardEnumBase, Gamestone::ActionEnumBase)
    REGISTER_CLASS_INIT2(Gamestone::MouseEnumBase, Gamestone::ActionEnumBase)
    REGISTER_CLASS_INIT1(Gamestone::EventEnumBase)
    REGISTER_CLASS_METHOD(Gamestone::ActionLogicalOR, "LogicalOR")
    REGISTER_CLASS_METHOD(Gamestone::ActionLogicalAND, "LogicalAND")
    REGISTER_CLASS_METHOD(Gamestone::ActionLogicalNOT, "LogicalNOT")
    REGISTER_CLASS_FOOTER()
    
    // Expose class
    REGISTER_CLASS_HEADER_CONSTRUCT(Gamestone::ActionCallback, "ActionCallback")
    REGISTER_CLASS_INIT1(PythonObject)
    REGISTER_CLASS_METHOD(&Gamestone::ActionCallback::SetCallback, "SetCallback")
    REGISTER_CLASS_METHOD(&Gamestone::ActionCallback::GetCallback, "GetCallback")
    REGISTER_CLASS_FOOTER()
}
