#ifndef OGG_CONFIG_H
#define OGG_CONFIG_H

#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1

#define SIZEOF_INT 4
#define SIZEOF_INT16_T 2
#define SIZEOF_INT32_T 4
#define SIZEOF_INT64_T 8
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SHORT 2
#define SIZEOF_UINT16_T 2
#define SIZEOF_UINT32_T 4
#define SIZEOF_U_INT16_T 2
#define SIZEOF_U_INT32_T 4

#define STDC_HEADERS 1

#endif
